import type { WorldProject } from "./types";

const now = new Date().toISOString();

export function createDefaultProject(): WorldProject {
  return {
    id: crypto.randomUUID(),
    name: "Untitled World",
    version: "0.1.0",
    createdAt: now,
    updatedAt: now,
    terrain: {
      width: 80,
      depth: 80,
      resolution: 65,
      heights: Array.from({ length: 65 * 65 }, (_, index) => {
        const x = index % 65;
        const z = Math.floor(index / 65);
        const dx = x / 64 - 0.5;
        const dz = z / 64 - 0.5;
        return Math.max(0, 1 - Math.hypot(dx * 1.6, dz * 1.6)) * 1.2;
      }),
      materialMap: Array.from({ length: 65 * 65 }, (_, index) => {
        const x = index % 65;
        if (x < 14) return "sand";
        if (x < 28) return "grass";
        if (x < 42) return "dirt";
        if (x < 52) return "rock";
        return "track";
      }),
    },
    materials: [
      { id: "grass", name: "Grass", color: "#84b96a", roughness: 0.95, scale: 1 },
      { id: "dirt", name: "Dirt", color: "#b18458", roughness: 1, scale: 1 },
      { id: "mud", name: "Mud", color: "#70513d", roughness: 1, scale: 1 },
      { id: "rock", name: "Rock", color: "#c7b49a", roughness: 0.9, scale: 1 },
      { id: "sand", name: "Sand", color: "#e0c97b", roughness: 1, scale: 1 },
      { id: "track", name: "Track", color: "#d8bc69", roughness: 1, scale: 1 },
    ],
    assets: [
      {
        id: "demo-tree",
        name: "Pine Tree",
        category: "Foliage",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/tree_pineTallA.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: true,
        tags: ["foliage", "tree", "pine"],
        placementRules: {
          paintEligible: true,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.8,
          maxScale: 1.4,
        },
      },
      {
        id: "demo-shrub",
        name: "Shrub Cluster",
        category: "Foliage",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/plant_bushSmall.png",
        defaultScale: 0.75,
        collisionType: "box",
        canPaint: true,
        tags: ["foliage", "bush", "shrub"],
        placementRules: {
          paintEligible: true,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.55,
          maxScale: 1,
        },
      },
      {
        id: "demo-rock",
        name: "Weathered Rock",
        category: "Props",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/rock_largeA.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: true,
        tags: ["rock", "stone", "boulder"],
        placementRules: {
          paintEligible: true,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.8,
          maxScale: 1.5,
        },
      },
      {
        id: "demo-boulder",
        name: "Boulder",
        category: "Props",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/rock_largeB.png",
        defaultScale: 1.2,
        collisionType: "box",
        canPaint: true,
        tags: ["rock", "stone", "boulder", "prop"],
        placementRules: {
          paintEligible: true,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.9,
          maxScale: 1.8,
        },
      },
      {
        id: "demo-cliff-large",
        name: "Cliff Wall",
        category: "Nature",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/cliff_large_rock.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["cliff", "rock", "wall", "ridge"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.9,
          maxScale: 1.4,
        },
      },
      {
        id: "demo-cliff-top",
        name: "Cliff Top",
        category: "Nature",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/cliff_top_rock.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["cliff", "rock", "wall", "ridge"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.85,
          maxScale: 1.25,
        },
      },
      {
        id: "demo-cliff-steps",
        name: "Cliff Steps",
        category: "Nature",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/cliff_steps_rock.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["cliff", "rock", "steps", "ridge"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.9,
          maxScale: 1.35,
        },
      },
      {
        id: "demo-cliff-corner",
        name: "Cliff Corner",
        category: "Nature",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/cliff_corner_rock.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["cliff", "rock", "corner", "ridge"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.85,
          maxScale: 1.2,
        },
      },
      {
        id: "demo-waterfall",
        name: "Waterfall Cliff",
        category: "Nature",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/cliff_waterfall_rock.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["cliff", "rock", "waterfall", "ridge"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.9,
          maxScale: 1.3,
        },
      },
      {
        id: "demo-sign",
        name: "Trail Marker",
        category: "Track",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/sign.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["barrier", "track", "sign", "post"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.8,
          maxScale: 1.2,
        },
      },
      {
        id: "demo-bridge",
        name: "Wooden Bridge",
        category: "Structure",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/bridge_woodRound.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["bridge", "wood", "track"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.9,
          maxScale: 1.15,
        },
      },
      {
        id: "demo-tower",
        name: "Lookout Tower",
        category: "Structure",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/tree_tall.png",
        defaultScale: 1.1,
        collisionType: "box",
        canPaint: false,
        tags: ["tower", "lookout", "structure"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.95,
          maxScale: 1.35,
        },
      },
      {
        id: "demo-tent",
        name: "Camp Tent",
        category: "Structure",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/tent_detailedClosed.png",
        defaultScale: 1,
        collisionType: "box",
        canPaint: false,
        tags: ["tent", "camp", "structure"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.85,
          maxScale: 1.2,
        },
      },
      {
        id: "demo-campfire",
        name: "Campfire",
        category: "Prop",
        filePath: "built-in",
        sourceType: "builtin",
        thumbnailPath: "/assets/kenney_nature-kit/Side/campfire_stones.png",
        defaultScale: 0.9,
        collisionType: "box",
        canPaint: false,
        tags: ["camp", "fire", "prop"],
        placementRules: {
          paintEligible: false,
          scatterEligible: true,
          alignToTerrain: true,
          minScale: 0.7,
          maxScale: 1,
        },
      },
    ],
    objects: [
      {
        id: "obj-demo-rock",
        assetId: "demo-rock",
        name: "Weathered Rock",
        position: { x: 8, y: 1.2, z: -4 },
        rotation: { x: 0, y: 0.4, z: 0 },
        scale: { x: 1.2, y: 1.2, z: 1.2 },
        layerId: "layer-props",
        visible: true,
        locked: false,
        collisionEnabled: true,
      },
      {
        id: "obj-demo-rock-2",
        assetId: "demo-rock",
        name: "Weathered Rock 2",
        position: { x: -10, y: 0.9, z: 12 },
        rotation: { x: 0, y: 1.2, z: 0 },
        scale: { x: 1, y: 1, z: 1 },
        layerId: "layer-props",
        visible: true,
        locked: false,
        collisionEnabled: true,
      },
      {
        id: "obj-demo-rock-3",
        assetId: "demo-rock",
        name: "Weathered Rock 3",
        position: { x: 14, y: 1.0, z: -6 },
        rotation: { x: 0, y: -0.2, z: 0 },
        scale: { x: 0.9, y: 0.9, z: 0.9 },
        layerId: "layer-props",
        visible: true,
        locked: false,
        collisionEnabled: true,
      },
      {
        id: "obj-demo-boulder",
        assetId: "demo-boulder",
        name: "Boulder",
        position: { x: -4, y: 0.8, z: -2 },
        rotation: { x: 0, y: 0.9, z: 0 },
        scale: { x: 1.35, y: 1.35, z: 1.35 },
        layerId: "layer-props",
        visible: true,
        locked: false,
        collisionEnabled: true,
      },
      {
        id: "obj-demo-sign",
        assetId: "demo-sign",
        name: "Trail Marker",
        position: { x: 3, y: 0.7, z: 2 },
        rotation: { x: 0, y: -0.1, z: 0 },
        scale: { x: 0.9, y: 0.9, z: 0.9 },
        layerId: "layer-props",
        visible: true,
        locked: false,
        collisionEnabled: true,
      },
    ],
    foliageGroups: [
      {
        id: "foliage-demo",
        name: "Pine Stand",
        assetIds: ["demo-tree", "demo-shrub"],
        instances: [
          {
            id: "foliage-tree-1",
            assetId: "demo-tree",
            position: { x: -16, y: 0.4, z: -10 },
            rotation: { x: 0, y: 0.5, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
          {
            id: "foliage-tree-2",
            assetId: "demo-tree",
            position: { x: -13, y: 0.45, z: -7 },
            rotation: { x: 0, y: 1.3, z: 0 },
            scale: { x: 1.1, y: 1.1, z: 1.1 },
          },
          {
            id: "foliage-tree-3",
            assetId: "demo-tree",
            position: { x: -18, y: 0.35, z: -6 },
            rotation: { x: 0, y: 2.2, z: 0 },
            scale: { x: 0.9, y: 0.9, z: 0.9 },
          },
          {
            id: "foliage-tree-4",
            assetId: "demo-tree",
            position: { x: -11, y: 0.55, z: -13 },
            rotation: { x: 0, y: 0.9, z: 0 },
            scale: { x: 1.2, y: 1.2, z: 1.2 },
          },
          {
            id: "foliage-tree-5",
            assetId: "demo-tree",
            position: { x: -8, y: 0.5, z: -8 },
            rotation: { x: 0, y: 2.7, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
          },
          {
            id: "foliage-shrub-1",
            assetId: "demo-shrub",
            position: { x: -15, y: 0.3, z: -12 },
            rotation: { x: 0, y: 1.7, z: 0 },
            scale: { x: 0.8, y: 0.8, z: 0.8 },
          },
          {
            id: "foliage-shrub-2",
            assetId: "demo-shrub",
            position: { x: -12, y: 0.3, z: -15 },
            rotation: { x: 0, y: 2.1, z: 0 },
            scale: { x: 0.7, y: 0.7, z: 0.7 },
          },
        ],
        settings: {
          density: 6,
          minSpacing: 3,
          randomScaleMin: 0.8,
          randomScaleMax: 1.3,
          randomRotation: true,
          slopeLimit: 35,
          avoidRoads: true,
          eraseMode: false,
        },
      },
    ],
    scatterZones: [],
    roads: [
      {
        id: "road-demo",
        name: "Forest Track",
        points: [
          { x: -24, y: 0.2, z: 8 },
          { x: -10, y: 0.2, z: 20 },
          { x: 8, y: 0.2, z: 18 },
          { x: 24, y: 0.2, z: 2 },
        ],
        width: 4.4,
        materialId: "track",
        flattenTerrain: true,
        smoothEdges: true,
        closedLoop: false,
        checkpointIds: [],
      },
    ],
    markers: [
      {
        id: "marker-start",
        type: "start-finish",
        name: "Start / Finish",
        position: { x: -24, y: 0.5, z: 8 },
      },
    ],
    environment: {
      backgroundColor: "#97c7ff",
      sunDirection: { x: 0.35, y: 1, z: 0.2 },
      sunIntensity: 2.1,
      ambientIntensity: 0.9,
      fogEnabled: true,
      fogColor: "#cfe8ff",
      fogDensity: 0.006,
      timeOfDay: "noon",
      weather: "clear",
    },
    layers: [
      { id: "layer-terrain", name: "Terrain", visible: true, locked: true },
      { id: "layer-props", name: "Props", visible: true, locked: false },
      { id: "layer-foliage", name: "Foliage", visible: true, locked: false },
      { id: "layer-road", name: "Roads", visible: true, locked: false },
      { id: "layer-markers", name: "Markers", visible: true, locked: false },
    ],
    metadata: {
      description: "Starter world generated from the MVP docs.",
      tags: ["showcase", "kenney"],
    },
  };
}
