import type { ShowcaseLayoutConfig } from "../../types";

export const DEFAULT_KENNEY_SHOWCASE_LAYOUT: ShowcaseLayoutConfig = {
  renderMode: "models",
  camera: {
    position: { x: 14, y: 18, z: 14 },
    target: { x: -1, y: 0.6, z: 0 },
    frustumHeight: 18,
    zoom: 1.05,
    backgroundColor: "#1a2836",
  },
  base: {
    center: { x: 0, z: 0 },
    levels: 6,
    tileFit: 5.9,
  },
  landmasses: [
    {
      center: { x: 0, z: 0 },
      levels: 6,
      tileFit: 5.9,
      yOffset: 0.0,
    },
    {
      center: { x: -16, z: 8 },
      levels: 4,
      tileFit: 4.6,
      yOffset: 0.02,
    },
    {
      center: { x: 18, z: -5 },
      levels: 4,
      tileFit: 4.7,
      yOffset: 0.02,
    },
    {
      center: { x: 7, z: 15 },
      levels: 3,
      tileFit: 3.8,
      yOffset: 0.04,
    },
  ],
  chains: [
    {
      kind: "path",
      points: [
        { x: -18, z: 17, y: 0.26 },
        { x: -12, z: 11, y: 0.32 },
        { x: -5, z: 6, y: 0.38 },
        { x: 3, z: 2, y: 0.36 },
        { x: 11, z: -3, y: 0.3 },
        { x: 18, z: -8, y: 0.26 },
      ],
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/ground_pathStraight.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_pathCorner.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_pathBend.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_pathOpen.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/path_wood.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/path_stone.glb",
      ],
      fit: 0.88,
      maxScale: 1.8,
    },
    {
      kind: "river",
      points: [
        { x: -23, z: 9, y: 0.08 },
        { x: -16, z: 5, y: 0.05 },
        { x: -9, z: 1, y: 0.03 },
        { x: -1, z: -1, y: 0.02 },
        { x: 8, z: -2, y: 0.02 },
        { x: 17, z: -5, y: 0.01 },
      ],
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverStraight.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverCorner.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverBend.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverOpen.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverEnd.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverTile.glb",
      ],
      fit: 0.86,
      maxScale: 1.6,
      yOffset: 0.01,
    },
    {
      kind: "bank",
      points: [
        { x: -24, z: 10, y: 0.04 },
        { x: -18, z: 6, y: 0.03 },
        { x: -11, z: 2, y: 0.02 },
        { x: -3, z: -1, y: 0.02 },
        { x: 9, z: -1, y: 0.02 },
        { x: 16, z: -3, y: 0.02 },
      ],
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverBendBank.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_pathBendBank.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/ground_riverRocks.glb",
      ],
      fit: 0.82,
      maxScale: 1.5,
      yOffset: -0.01,
    },
  ],
  rings: [
    {
      center: { x: -1.5, z: 0.5 },
      radiusX: 15.8,
      radiusZ: 12.6,
      count: 24,
      y: 0.08,
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_block_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_block_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_corner_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_corner_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_half_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_half_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_steps_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_steps_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_top_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_top_rock.glb",
      ],
      fit: 4.85,
      wobble: 0.28,
      maxScale: 1.6,
    },
    {
      center: { x: 9, z: 4 },
      radiusX: 11,
      radiusZ: 8,
      count: 16,
      y: 0.1,
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_block_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_block_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_corner_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_corner_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_half_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_half_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_steps_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_steps_rock.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_top_stone.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/cliff_top_rock.glb",
      ],
      fit: 4.0,
      wobble: 0.22,
      maxScale: 1.55,
    },
    {
      center: { x: -3, z: 3 },
      radiusX: 20,
      radiusZ: 15.5,
      count: 16,
      y: 0.43,
      modelPaths: [
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineTallA.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineTallB.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineTallC.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineTallD.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineRoundA.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_pineRoundB.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_small.glb",
        "/assets/kenney_nature-kit/Models/GLTF format/tree_oak.glb",
      ],
      fit: 5.4,
      wobble: 0.14,
      maxScale: 1.9,
    },
  ],
  clusters: [
    {
      kind: "tree",
      center: { x: -18, y: 0.18, z: 14 },
      radius: 8.4,
      count: 14,
      fit: 5.0,
      maxScale: 1.9,
    },
    {
      kind: "tree",
      center: { x: -7, y: 0.14, z: 5 },
      radius: 5.6,
      count: 18,
      fit: 4.5,
      maxScale: 1.85,
    },
    {
      kind: "tree",
      center: { x: 8, y: 0.12, z: 6 },
      radius: 4.8,
      count: 16,
      fit: 4.0,
      maxScale: 1.8,
    },
    {
      kind: "tree",
      center: { x: 13, y: 0.16, z: -10 },
      radius: 5.8,
      count: 14,
      fit: 4.4,
      maxScale: 1.8,
    },
    {
      kind: "rock",
      center: { x: -16, y: 0.1, z: 8 },
      radius: 5.8,
      count: 10,
      fit: 3.0,
      maxScale: 1.5,
    },
    {
      kind: "rock",
      center: { x: 18, y: 0.12, z: 4 },
      radius: 5.0,
      count: 8,
      fit: 2.8,
      maxScale: 1.45,
    },
    {
      kind: "camp",
      center: { x: 22, y: 0.18, z: 10 },
      radius: 2.8,
      count: 5,
      fit: 1.8,
      maxScale: 1.5,
    },
    {
      kind: "fence",
      center: { x: 21, y: 0.18, z: 10 },
      radius: 3.8,
      count: 6,
      fit: 1.55,
      maxScale: 1.35,
    },
    {
      kind: "sign",
      center: { x: 12, y: 0.2, z: 6 },
      radius: 1.2,
      count: 1,
      fit: 1.4,
      maxScale: 1.2,
    },
  ],
  heroProps: [
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/bridge_woodRound.glb",
      x: -2,
      y: 0.6,
      z: 0.4,
      rotationY: Math.PI / 4,
      fit: 4.4,
      maxScale: 1.9,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/bridge_stoneNarrow.glb",
      x: -1.1,
      y: 0.6,
      z: 0.0,
      rotationY: Math.PI / 4,
      fit: 4.1,
      maxScale: 1.8,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/tent_smallOpen.glb",
      x: 20,
      y: 0.2,
      z: 12,
      rotationY: -Math.PI / 2,
      fit: 1.9,
      maxScale: 1.55,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/campfire_stones.glb",
      x: 17,
      y: 0.16,
      z: 10,
      rotationY: Math.PI / 4,
      fit: 1.4,
      maxScale: 1.4,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/fence_simpleLow.glb",
      x: 22,
      y: 0.18,
      z: 9,
      rotationY: Math.PI / 2,
      fit: 1.5,
      maxScale: 1.4,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/sign.glb",
      x: 12,
      y: 0.2,
      z: 5,
      rotationY: Math.PI / 4,
      fit: 1.4,
      maxScale: 1.2,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/cliff_waterfallTop_stone.glb",
      x: -16,
      y: 0.42,
      z: 5,
      rotationY: Math.PI / 2,
      fit: 4.2,
      maxScale: 1.6,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/cliff_waterfall_stone.glb",
      x: -16,
      y: 0.16,
      z: 3,
      rotationY: Math.PI / 2,
      fit: 4.0,
      maxScale: 1.6,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/cliff_large_stone.glb",
      x: -20,
      y: 0.38,
      z: 10,
      rotationY: Math.PI / 2,
      fit: 4.4,
      maxScale: 1.6,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/cliff_cornerTop_stone.glb",
      x: 20,
      y: 0.38,
      z: -7,
      rotationY: -Math.PI / 2,
      fit: 4.1,
      maxScale: 1.6,
    },
    {
      path: "/assets/kenney_nature-kit/Models/GLTF format/cliff_steps_stone.glb",
      x: 10,
      y: 0.24,
      z: -15,
      rotationY: 0,
      fit: 4.0,
      maxScale: 1.5,
    },
  ],
};
